### ISSUE TITLE
Add an option to just plot points rather than a line

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#348]
Some users would like to be able to have no line connecting their data points. It looks like MPlot is capable of this, it probably just needs to be exposed at the user level.

**Comment by iainworkman** [comment]
Added PMV drawLines to MPlotSeriesBasic:
- Added drawLines_ to MPlotSeriesBasic
- Added drawLines() and setDrawLines(...) to MPlotSeriesBasic
- Altered MPlotSeriesBasic::MPlotSeriesBasic() to set default value for drawLines_ to true
- Altered MPlotSeriesBasic::paint(...) to only paint lines if drawLines_ is true

https://github.com/acquaman/MPlot/commit/2364d3ecd03f47d3eeb4ce4e31cd345d629f9c34

**Comment by dretrex** [comment]
Cool.  From the looks of it, do we only need to add a way to toggle that inside the scan view?  If so, I'm sure we can add it to the plot settings popup or something.

**Comment by iainworkman** [comment]
Yeah, that was my plan but I needed to do a clean build of AM to bring across the changes to MPlot. That's done now so I should be able to play around with the AM stuff this morning.

**Comment by iainworkman** [comment]
Updated names of widgets in AMLinePropertyEditor to meet AM standards

a1b4ba9db1d6c79d169d384e56e7a648d6c86811

**Comment by iainworkman** [comment]
Added ui elements and signal to AMLinePropertyEditor to allow for plotting of just points, instead of points and lines

3325e134b16921c7af6e442b788717d187057fd7

**Comment by iainworkman** [comment]
Added properties controlling whether or not to plot a line or just points to AMScanSetModel, AMScanSetItemPropertyDialog and AMDataSourcePlotSettings

f43d24459597ee5717268a1cbb7314b5c4e71309

**Comment by iainworkman** [comment]
Now I've got the code set up and can see results, I've been examining this approach again from a user perspective, and think a slightly different tack might be better (one, in fact, which doesn't require any changes to MPlot). 

MPlotSeries contains methods to set the marker style (none, circle, cross, diagonal line etc.), a pen colour and a brush colour for the marker. By adding these options to the AMLineProperty editor the user will have a bunch of choices of how they wish to show both the markers and the lines. I will keep defaults at their current state (line, no markers).

The only other issue is that MPlot, from what I can tell, draws a marker at each discrete data point. This usually leads to most plots being overwhelmed with a whole load of data points. I'm not sure what would be the best way of handling this; maybe only plotting one out of every N points, or only plotting points when the value is sufficiently altered from the previous point. Not sure.

**Comment by davidChevrier** [comment]
@iainworkman I think one of the reasons why the markers aren't normally turned on is because in the beginning we noticed that issue. If you have a good idea as to how to address it, all the power to you.

**Comment by dretrex** [comment]
I think the desire to look at points rather than lines comes from trying to look at subsets of an overall data set.  Therefore, the default is what we have now where there is only lines and no markers, but then they want to look at the scan with points only where the whole scan doesn't look that great but then they zoom in to look at a key piece of the data.  That's why it would be "best" if it was easy to switch between them.

Then again, I have never had anyone specifically ask me for this feature and the above is just my conjecture.

**Comment by iainworkman** [comment]
Okay, rolled back the changes made to this point in order to get everything done right. This time I've started working from the basis of a redesign on AMLinePropertyEditor and getting this correct with respect to the options which this is going to need from a usability perspective.

**Comment by iainworkman** [comment]
Added Combo boxes specifically designed for letting users choose PenLineStyles and Marker Shapes. Added these combo boxes to AMLineProperty Editor

521259f02a9731ebebcebe3c42713fcdfd1e29d0

As an aside there is an argument to be made for transferring the AMPlotMarkerComboBox over to be in MPlot.

**Comment by iainworkman** [comment]
Setup AMLineProperty editory to emit signals on changes to the marker settings which are listened to, and ultimately passed to MPlotSeries by:
> AMLinePropertyEditor >> AMScanSetItemPropertyDialog >> AMScanSetModel >> AMScanView >> AMDataSourcePlotSettings >> MPlotSeries

588999438a0ee3ee9073bf0c5be719b0cf23f5e5

**Comment by davidChevrier** [comment]
@iainworkman I just pushed some changes up to the remote branch (just merges to master to make it so we can auto-merge from the pull request later). Would you mind looking into that transparent background and white text issue? That way I can build again and get this pulled in. Were there any changes to MPlot for this?

**Comment by iainworkman** [comment]
Nope. Everything that was needed was already there in MPlot, thankfully.

-----Original Message-----

**Comment by iainworkman** [comment]
Changed order of PMVs in AMDataSourcePlotSettings as they were being constructed out of order. Which is bad.

18373ab939e429d63a04abbddc4c4a05b5eb6c0e

**Comment by iainworkman** [comment]
Altered:
- AMDataSourcePlotSettings ~ Reordered the constructor subcalls again, as the last attempt didn't solve the issue.
- AMLinePropertyEditor.cpp ~ Set the stylesheet to set the background color to black because this wasn't happening on all machines (Macs, for instance, we're inheriting a background of alpha from somewhere)

a19e163492623ce1e90f6ea33fedb3409fad8526

**Comment by davidChevrier** [comment]
Done in b9e9bd9

@iainworkman time estimate?

**Comment by iainworkman** [comment]
About 30 hours total :(
